### ISSUE TITLE
Semigroup and Monoid instances

### ISSUE THREAD

**Issue by jedahu** [garyb/purescript-integers#1]
Glad this project exists! Do you intend to add semigroup and monoid instances?

**Comment by garyb** [comment]
There's actually a PR pending for `purescript-monoid` that introduces `Additive` and `Multiplicative` newtypes that have `Semigroup` and `Monoid` defined for any `Semiring`, so those will also work for `Int`s :)

See here: purescript/purescript-monoid#9

Just a note of warning - at the moment using `purescript-integers` probably won't perform very well, I'm waiting for rewrite rules to become available and then will move the project over to the main `purescript` org.

**Comment by jedahu** [comment]
Ah. Excellent!
